s="python is easy"
m1=s.find("s")
print(m1)
print("*******************")
m2=s.rfind("s")
print(m2)
print("*******************")
m3=s.index("o")
print(m3)
print("*******************")
m4=s.rindex("s")
print(m4)
print("*******************")
m5=s.count("s")
print(m5)
print("*******************")
