s="python is one the lang in python java is easy"
m1=s.lstrip("python")
print(m1)
print("---------------------------------------")
m2=s.rsplit("easy")
print(m2)
print("---------------------------------------")
m3=s.strip("is")
print(m3)
print("---------------------------------------")